# Generated by Django 4.2.1 on 2023-05-19 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_room_time_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RemoveField(
            model_name='message',
            name='date_added',
        ),
        migrations.AlterField(
            model_name='room',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 5, 19, 12, 11, 48, 484175)),
        ),
    ]
